# Generated by Django 4.1.3 on 2022-11-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ST', 'STOCKS'), ('FU', 'FUTURES'), ('FO', 'FOREX'), ('CR', 'CRYPTO'), ('IN', 'INDICES'), ('BO', 'BONDS'), ('EC', 'ECONOMY')], default='ST', max_length=2)),
                ('api', models.CharField(max_length=512)),
            ],
        ),
    ]
